apiVersion: v1
kind: Secret
metadata:
  name: repo-github-https-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
stringData:
  type: git
  url: xxx
  username: xxx
  password: xxxx
